id: I7C41CD81
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T05:09:58+00:00'
last_modified: '2022-06-08T02:20:43.728535+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4004
  title: ཕྱག་རྒྱ་ཆེན་མོ་རྡོ་རྗེ་ཡེ་ཤེས་ཀྱི་སིནྡྷུ་རའི་དཀྱིལ་འཁོར་ལས། ཇོ་མོ་ལྷན་ཅིག་སྐྱེས་མའི་སྒྲུབ་ཐབས་དངོས་གྲུབ་ཀྱི་འདོད་འཇོ་སོགས་ཆོས་ཚན་ཁག་ཅིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FB0C:
      image_group_id: I1KG4078
      title: ''
      total_pages: 398
      order: 1
      base_file: FB0C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
