id: P004617
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:44:38.753679
source_metadata:
  id: bdr:W1KG4004
  title: ཕྱག་རྒྱ་ཆེན་མོ་རྡོ་རྗེ་ཡེ་ཤེས་ཀྱི་སིནྡྷུ་རའི་དཀྱིལ་འཁོར་ལས། ཇོ་མོ་ལྷན་ཅིག་སྐྱེས་མའི་སྒྲུབ་ཐབས་དངོས་གྲུབ་ཀྱི་འདོད་འཇོ་སོགས་ཆོས་ཚན་ཁག་ཅིག་
  author: ''
  volumes:
    c91ef5a74ad74cad88981acee3180a56:
      image_group_id: I1KG4078
      title: ''
      volume_number: 1
      total_pages: 398
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
