id: opecha:P004617
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4004
  title: ཕྱག་རྒྱ་ཆེན་མོ་རྡོ་རྗེ་ཡེ་ཤེས་ཀྱི་སིནྡྷུ་རའི་དཀྱིལ་འཁོར་ལས། ཇོ་མོ་ལྷན་ཅིག་སྐྱེས་མའི་སྒྲུབ་ཐབས་དངོས་གྲུབ་ཀྱི་འདོད་འཇོ་སོགས་ཆོས་ཚན་ཁག་ཅིག་
  volume: ''
  author: ''
