id: P004617
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4004
  title: ཕྱག་རྒྱ་ཆེན་མོ་རྡོ་རྗེ་ཡེ་ཤེས་ཀྱི་སིནྡྷུ་རའི་དཀྱིལ་འཁོར་ལས། ཇོ་མོ་ལྷན་ཅིག་སྐྱེས་མའི་སྒྲུབ་ཐབས་དངོས་གྲུབ་ཀྱི་འདོད་འཇོ་སོགས་ཆོས་ཚན་ཁག་ཅིག་
  author: ''
  volumes:
    c91ef5a74ad74cad88981acee3180a56:
      image_group_id: I1KG4078
      title: ''
      volume_number: 1
      total_pages: 398
      base_file: v001.txt
